# Generated by Django 2.1.3 on 2019-11-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(default=None),
        ),
    ]
