# Generated by Django 2.1.3 on 2019-11-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191109_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
