# Generated by Django 2.1.3 on 2019-11-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20191109_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='No Title', max_length=200),
        ),
    ]
