# Generated by Django 2.1.3 on 2019-11-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20191109_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
