# Generated by Django 2.1.3 on 2019-11-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20191109_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=199, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, default='', max_length=99, null=True),
        ),
    ]
