# Generated by Django 2.1.3 on 2019-11-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20191109_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(max_length=99, upload_to='images'),
        ),
    ]
